"use strict";

const $ = (sel) => document.querySelector(sel);
const form = $("#form");
const input = $("#doi");
const goBtn = $("#go");
const stage = $("#stage");

const DOISHOT_MARK = `generated by DOIshot (build ${(window.__DOISHOT_CONFIG || {}).BUILD || "dev"})`;

/* ---------- DOI normalization ---------- */
// arXiv ids resolve to their DataCite-registered DOI (prefix 10.48550). The
// registered DOI is version-less, so we drop any trailing "v2".
function arxivToDoi(id) {
  return "10.48550/arXiv." + id.trim().replace(/\.pdf$/i, "").replace(/v\d+$/i, "");
}

// Accepts: raw DOIs, doi.org URLs, "doi:" prefixes, arXiv URLs/ids/bare ids,
// Nature article URLs, and most publisher URLs (which embed the DOI in the path).
function normalizeDoi(raw) {
  if (!raw) return null;
  let s = raw.trim();

  // --- arXiv ---
  const arxivUrl = s.match(/arxiv\.org\/(?:abs|pdf)\/([^\s?#]+)/i);
  if (arxivUrl) return arxivToDoi(arxivUrl[1]);
  const arxivPrefix = s.match(/^arxiv:\s*(.+)$/i);
  if (arxivPrefix) return arxivToDoi(arxivPrefix[1]);
  // bare new-style id (2303.08774, optional version), whole string only
  if (/^\d{4}\.\d{4,5}(v\d+)?$/i.test(s)) return arxivToDoi(s);
  // bare old-style id (hep-th/9901001), whole string only
  if (/^[a-z][a-z.-]+\/\d{7}(v\d+)?$/i.test(s)) return arxivToDoi(s);

  // --- Nature article URLs carry no DOI in the path: /articles/<id> -> 10.1038/<id> ---
  const nature = s.match(/nature\.com\/articles\/([a-z0-9-]+)/i);
  if (nature) return "10.1038/" + nature[1].replace(/\.pdf$/i, "");

  // --- Strip doi.org / doi: wrappers ---
  s = s.replace(/^https?:\/\/(dx\.)?doi\.org\//i, "");
  s = s.replace(/^doi:\s*/i, "");

  // --- Any embedded DOI: covers doi.org plus most publisher URLs
  // (APS, Science, Springer, Wiley, IOP, …) which put the DOI in the path. ---
  const m = s.match(/10\.\d{4,9}\/[^\s"'<>]+/);
  if (m) return decodeURIComponent(m[0]).replace(/[).,;]+$/, "");
  return null;
}

/* ---------- Helpers ---------- */
function stripTags(str) {
  if (!str) return "";
  const cleaned = str
    .replace(/<jats:title[^>]*>.*?<\/jats:title>/gi, "")
    .replace(/<\/?[^>]+>/g, " ");
  const doc = new DOMParser().parseFromString(cleaned, "text/html");
  return (doc.body.textContent || "").replace(/\s+/g, " ").trim();
}

function safeHttpUrl(url, fallback) {
  const s = String(url ?? "").trim();
  if (/^https?:\/\//i.test(s)) return s;
  return fallback;
}

function esc(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
  );
}

function authorName(a) {
  if (a.name) return a.name; // DataCite literal
  const given = a.given || a.givenName || "";
  const family = a.family || a.familyName || "";
  const full = `${given} ${family}`.trim();
  return full || a.literal || "";
}

function yearFromDateInput(partsOrIso) {
  if (!partsOrIso) return "";
  if (typeof partsOrIso === "string") {
    const m = partsOrIso.match(/^(\d{4})/);
    return m ? m[1] : "";
  }
  return partsOrIso[0] ? String(partsOrIso[0]) : "";
}

function formatPublicationDate(partsOrIso) {
  if (!partsOrIso) return "";
  let y = 0;
  let mo = 0;
  let d = 0;
  if (typeof partsOrIso === "string") {
    const m = partsOrIso.match(/^(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?/);
    if (!m) return "";
    y = Number(m[1]);
    mo = m[2] ? Number(m[2]) : 0;
    d = m[3] ? Number(m[3]) : 0;
  } else {
    [y, mo, d] = partsOrIso;
    if (!y) return "";
  }
  if (mo && d) {
    return new Intl.DateTimeFormat("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(new Date(Date.UTC(y, mo - 1, d)));
  }
  if (mo) {
    return new Intl.DateTimeFormat("en-GB", {
      month: "long",
      year: "numeric",
    }).format(new Date(Date.UTC(y, mo - 1, 1)));
  }
  return String(y);
}

function datePartsFromCrossref(m) {
  const fields = [m["published-online"], m["published-print"], m.issued];
  let best = null;
  for (const field of fields) {
    const parts = field && field["date-parts"];
    if (!parts || !parts[0] || !parts[0][0]) continue;
    if (!best || parts[0].length > best.length) best = parts[0];
  }
  return best;
}

function dateFromDataCite(a) {
  const preferred = (a.dates || []).find((entry) =>
    /^(issued|published|available|updated)$/i.test(entry.dateType || "")
  );
  if (preferred && preferred.date) return preferred.date;
  if (a.publicationYear) return String(a.publicationYear);
  return "";
}

function formatAuthors(authors) {
  const names = (authors || []).map(authorName).filter(Boolean);
  if (!names.length) return "";
  const CAP = 18;
  if (names.length <= CAP) return esc(names.join(", "));
  const shown = names.slice(0, CAP).join(", ");
  return `${esc(shown)} <span class="more">+ ${names.length - CAP} more</span>`;
}

/* ---------- Source resolvers ---------- */
async function fromCrossref(doi) {
  const r = await fetch(`https://api.crossref.org/works/${encodeURIComponent(doi)}`);
  if (!r.ok) throw new Error("crossref " + r.status);
  const m = (await r.json()).message;
  const dateParts = datePartsFromCrossref(m);
  return {
    source: "crossref",
    title: (m.title && m.title[0]) || "Untitled",
    authors: m.author || [],
    container: (m["container-title"] && m["container-title"][0]) || "",
    publisher: m.publisher || "",
    date: formatPublicationDate(dateParts),
    year: yearFromDateInput(dateParts),
    type: prettyType(m.type),
    abstract: stripTags(m.abstract),
    doi: m.DOI || doi,
    url: safeHttpUrl(m.URL, `https://doi.org/${doi}`),
  };
}

async function fromDataCite(doi) {
  const r = await fetch(`https://api.datacite.org/dois/${encodeURIComponent(doi)}`);
  if (!r.ok) throw new Error("datacite " + r.status);
  const a = (await r.json()).data.attributes;
  const abs = (a.descriptions || []).find(
    (d) => (d.descriptionType || "").toLowerCase() === "abstract"
  ) || (a.descriptions || [])[0];
  const dateRaw = dateFromDataCite(a);
  return {
    source: "datacite",
    title: (a.titles && a.titles[0] && a.titles[0].title) || "Untitled",
    authors: a.creators || [],
    container: (a.container && a.container.title) || "",
    publisher: a.publisher || "",
    date: formatPublicationDate(dateRaw),
    year: yearFromDateInput(dateRaw),
    type:
      prettyType(a.types && (a.types.resourceTypeGeneral || a.types.resourceType)) ||
      "Dataset",
    abstract: stripTags(abs && abs.description),
    doi: a.doi || doi,
    url: safeHttpUrl(a.url, `https://doi.org/${doi}`),
  };
}

function prettyType(t) {
  if (!t) return "";
  const map = {
    "journal-article": "Journal article",
    "posted-content": "Preprint",
    "proceedings-article": "Conference paper",
    "book-chapter": "Book chapter",
    Text: "Article",
    Preprint: "Preprint",
  };
  return map[t] || String(t).replace(/-/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}

function uniq(list) {
  const seen = new Set();
  return list.filter((x) => x && !seen.has(x) && seen.add(x));
}

// Affiliations embedded in the registration-agency record (often sparse, and
// for arXiv's auto-generated DataCite deposits sometimes outright corrupt: a
// single stray string gets duplicated onto every creator regardless of their
// real affiliation, e.g. hundreds of authors all showing "Rai"). Detect that
// failure mode — one value covering nearly all of a large author list — and
// drop just that value rather than surface it as fact, keeping any genuine
// minority affiliations alongside it.
function affiliationsFrom(authors) {
  const out = [];
  for (const a of authors || [])
    for (const aff of a.affiliation || [])
      out.push(typeof aff === "string" ? aff : aff && aff.name);
  const filtered = out.filter(Boolean);
  if (filtered.length > 20) {
    const counts = new Map();
    for (const f of filtered) counts.set(f, (counts.get(f) || 0) + 1);
    const bogus = new Set();
    for (const [value, count] of counts)
      if (count / filtered.length > 0.9) bogus.add(value);
    if (bogus.size) return uniq(filtered.filter((f) => !bogus.has(f)));
  }
  return uniq(filtered);
}

// Many publishers (APS journals, Nature, …) don't deposit abstracts with
// Crossref, and affiliations are often missing too. OpenAlex has both (abstract
// as an inverted index, clean institution names) and is CORS-enabled. Free, no
// key. One call enriches both fields.
async function enrichFromOpenAlex(doi) {
  const empty = { abstract: "", affiliations: [], publicationDate: "" };
  try {
    const r = await fetch(
      `https://api.openalex.org/works/doi:${encodeURIComponent(doi)}` +
        `?select=abstract_inverted_index,authorships,publication_date`
    );
    if (!r.ok) return empty;
    const w = await r.json();
    let abstract = "";
    if (w.abstract_inverted_index) {
      const words = [];
      for (const [word, positions] of Object.entries(w.abstract_inverted_index))
        for (const i of positions) words[i] = word;
      abstract = words.join(" ").replace(/\s+/g, " ").trim();
    }
    const affiliations = uniq(
      (w.authorships || []).flatMap((au) =>
        (au.institutions || []).map((i) => i.display_name)
      )
    );
    return {
      abstract,
      affiliations,
      publicationDate: w.publication_date || "",
    };
  } catch (_) {
    return empty;
  }
}

async function resolve(doi) {
  // Enrich from OpenAlex in parallel; adds no latency in the common path, and
  // never throws (returns empties on failure).
  const enrichment = enrichFromOpenAlex(doi);
  let data;
  try {
    data = await fromCrossref(doi);
  } catch (_) {
    data = await fromDataCite(doi); // arXiv, datasets, software, etc.
  }
  const enr = await enrichment;
  // Prefer OpenAlex's clean institution names over the verbose / sparse
  // affiliation strings embedded in agency records; fall back to those.
  data.affiliations = enr.affiliations.length ? enr.affiliations : affiliationsFrom(data.authors);
  if (!data.abstract) data.abstract = enr.abstract;
  if (enr.publicationDate && (!data.date || /^\d{4}$/.test(data.date))) {
    data.date = formatPublicationDate(enr.publicationDate);
    data.year = yearFromDateInput(enr.publicationDate);
  }
  return data;
}

/* ---------- Source-aware theming ----------
 *
 * Two tiers:
 *  - "branded": journals whose real identity we ship locally — official
 *    wordmark/logo (assets/journals/…), the journal's actual web fonts
 *    fonts the journals themselves use), and colors sampled from each
 *    journal's live stylesheet.
 *  - "badge": long-tail publishers, kept as the old colored-badge look.
 *
 * Ground truth (extracted 2026-07 from each site's CSS):
 *  - nature.com     -> Palatino serif stack (Harding is proprietary), links #025e8d, meta #626262
 *  - journals.aps.org -> Noto Sans, links #00538b, ink #2e2f35 (unified 2024 design)
 *  - quantum-journal.org -> Raleway headings (600) + Open Sans, purple #53257f / cyan #03c4eb
 *  - arxiv.org      -> Lucida Grande system stack, arXiv red #b31b1b
 *  - science.org    -> hard-blocks non-browsers; official wordmark + brand red
 *                      #c8102e with close free fonts (approximation).
 */
const ASSETS = "assets/journals";

const DEFAULT_THEME = {
  kind: "badge",
  color: "#2563eb",
  titleFont: "Source Serif 4",
  bodyFont: "Source Sans 3",
  titleWeight: "700",
  titleSpacing: "-0.01em",
};

const NATURE_BASE = {
  kind: "branded",
  color: "#025e8d",            // nature.com link blue
  titleFont: "Palatino Linotype",
  bodyFont: "Palatino Linotype",
  metaFont: "Merriweather Sans",
  // NB: no double quotes anywhere in these values - they are injected into an
  // inline style="…" attribute (unquoted multi-word family names are valid CSS).
  titleFallback: "Palatino, Georgia, Times New Roman, serif",
  bodyFallback: "Palatino, Georgia, Times New Roman, serif",
  googleFonts: "family=Merriweather+Sans:wght@400;700",
  titleWeight: "700",
  titleSpacing: "-0.005em",
  titleColor: "#222222",
  textColor: "#222222",
  metaColor: "#626262",
  rule: "#000000",
  ruleWidth: "2px",
  topbar: "#000000",
  topbarHeight: "0px",
  logoHeight: "1.6em",
};

const APS_BASE = {
  kind: "branded",
  color: "#00538b",            // APS blue (links, accents)
  titleFont: "Noto Sans",
  bodyFont: "Noto Sans",
  metaFont: "Noto Sans",
  googleFonts: "family=Noto+Sans:ital,wght@0,400;0,600;0,700;1,400",
  titleWeight: "700",
  titleSpacing: "-0.01em",
  titleColor: "#2e2f35",
  textColor: "#2e2f35",
  metaColor: "#6b6b6c",
  rule: "#00538b",
  ruleWidth: "2px",
  topbarHeight: "0px",
  logo: `${ASSETS}/aps/logo.svg`,
  logoHeight: "2.1em",
};

// Ordered rules: first match wins.
const JOURNAL_THEME_RULES = [
  {
    // arXiv abs-page look: Lucida Grande stack, arXiv red, official logo.
    match: (d) => /^10\.48550\/arxiv/i.test(d.doi),
    theme: {
      kind: "branded",
      color: "#b31b1b",
      titleFont: "Lucida Grande",
      bodyFont: "Lucida Grande",
      metaFont: "Lucida Grande",
      titleFallback: "Lucida Sans Unicode, Helvetica Neue, Helvetica, Arial, sans-serif",
      bodyFallback: "Lucida Sans Unicode, Helvetica Neue, Helvetica, Arial, sans-serif",
      googleFonts: "",
      titleWeight: "700",
      titleSpacing: "0",
      titleColor: "#1a1a1a",
      textColor: "#1a1a1a",
      metaColor: "#6b6b6b",
      rule: "#b31b1b",
      ruleWidth: "2px",
      topbarHeight: "0px",
      logo: `${ASSETS}/arxiv/logo.svg`,
      logoHeight: "2.0em",
      label: "arXiv",
    },
  },
  {
    // quantum-journal.org: Raleway 600 headings, Open Sans body,
    // purple #53257f + cyan #03c4eb from their theme stylesheet.
    match: (d) =>
      /^10\.22331\//i.test(d.doi) ||
      /^quantum$/i.test((d.container || "").trim()),
    theme: {
      kind: "branded",
      color: "#53257f",
      titleFont: "Raleway",
      bodyFont: "Open Sans",
      metaFont: "Open Sans",
      googleFonts: "family=Raleway:wght@400;600;700&family=Open+Sans:ital,wght@0,400;0,600;1,400",
      titleWeight: "600",
      titleSpacing: "-0.01em",
      titleColor: "#2d2d2d",
      textColor: "#333333",
      metaColor: "#6b6b6b",
      rule: "#03c4eb",
      ruleWidth: "3px",
      topbarHeight: "0px",
      logo: `${ASSETS}/quantum/logo.png`,
      logoHeight: "2.0em",
      label: "Quantum",
    },
  },
  {
    // nature.com: Palatino serif stack (Harding is proprietary), official
    // per-journal wordmark SVGs for Nature & Nature Physics; sibling titles
    // get a serif text wordmark.
    match: (d) => /^10\.1038\//i.test(d.doi) || /^nature( |$)/i.test(d.container || ""),
    theme: (d) => {
      const c = (d.container || "").trim();
      if (/^nature$/i.test(c) || !c)
        return { ...NATURE_BASE, logo: `${ASSETS}/nature/logo.svg`, label: "Nature" };
      if (/^nature physics$/i.test(c))
        return { ...NATURE_BASE, logo: `${ASSETS}/nature-physics/logo.svg`, logoHeight: "1.45em", label: "Nature Physics" };
      return { ...NATURE_BASE, wordmark: c.toLowerCase(), label: c };
    },
  },
  {
    // science.org blocks all non-browser access; official AAAS wordmark +
    // Science red, fonts are close free stand-ins.
    match: (d) => /^10\.1126\//i.test(d.doi) || /^science( advances| immunology| robotics|$)/i.test(d.container || ""),
    theme: {
      kind: "branded",
      color: "#c8102e",
      titleFont: "Source Serif 4",
      bodyFont: "Libre Franklin",
      metaFont: "Libre Franklin",
      googleFonts: "family=Source+Serif+4:opsz,wght@8..60,600;8..60,700&family=Libre+Franklin:wght@400;600",
      titleWeight: "700",
      titleSpacing: "-0.01em",
      titleColor: "#1c1c1c",
      textColor: "#2a2a2a",
      metaColor: "#6b6b6b",
      rule: "#c8102e",
      ruleWidth: "3px",
      topbarHeight: "0px",
      logo: `${ASSETS}/science/logo.svg`,
      logoHeight: "1.9em",
      label: "Science",
    },
  },
  {
    // journals.aps.org unified 2024 design: Noto Sans + APS blue; the
    // masthead pairs the APS logo with the journal's name (PRX, PRA, PRX
    // Quantum, PRL, … all resolve here via their container title).
    match: (d) => /^10\.1103\//i.test(d.doi) || /^(physical review|phys\.? rev\.?|prx)/i.test(d.container || ""),
    theme: (d) => ({
      ...APS_BASE,
      journalName: d.container || "Physical Review",
      label: d.container || "Physical Review",
    }),
  },
  {
    match: (d) => /^10\.1073\//i.test(d.doi) || /pnas/i.test(d.container || ""),
    theme: {
      color: "#2e6da4",
      titleFont: "Libre Baskerville",
      bodyFont: "Source Sans 3",
      titleWeight: "700",
      titleSpacing: "0",
      label: "PNAS",
    },
  },
  {
    match: (d) => /^10\.1021\//i.test(d.doi) || /acs /i.test(d.container || ""),
    theme: {
      color: "#006298",
      titleFont: "IBM Plex Serif",
      bodyFont: "IBM Plex Sans",
      titleWeight: "600",
      titleSpacing: "0",
    },
  },
  {
    match: (d) => /^10\.1039\//i.test(d.doi),
    theme: {
      color: "#d6083b",
      titleFont: "Spectral",
      bodyFont: "Source Sans 3",
      titleWeight: "600",
      titleSpacing: "0",
      label: "RSC",
    },
  },
  {
    match: (d) => /^10\.1088\//i.test(d.doi),
    theme: {
      color: "#003b5c",
      titleFont: "Roboto Slab",
      bodyFont: "Roboto",
      titleWeight: "700",
      titleSpacing: "0",
      label: "IOP",
    },
  },
  {
    match: (d) => /^10\.1364\//i.test(d.doi) || /optica/i.test(d.container || ""),
    theme: {
      color: "#0072ce",
      titleFont: "Montserrat",
      bodyFont: "Open Sans",
      titleWeight: "700",
      titleSpacing: "-0.02em",
      label: "Optica",
    },
  },
  {
    match: (d) => /^10\.1007\//i.test(d.doi) || /springer/i.test(d.publisher || ""),
    theme: {
      color: "#004b87",
      titleFont: "Merriweather",
      bodyFont: "Open Sans",
      titleWeight: "700",
      titleSpacing: "0",
    },
  },
  {
    match: (d) => /^10\.1016\//i.test(d.doi) || /elsevier/i.test(d.publisher || ""),
    theme: {
      color: "#e9711c",
      titleFont: "Roboto",
      bodyFont: "Roboto",
      titleWeight: "700",
      titleSpacing: "-0.01em",
    },
  },
  {
    match: (d) => /^10\.1002\//i.test(d.doi) || /wiley/i.test(d.publisher || ""),
    theme: {
      color: "#585858",
      titleFont: "Lora",
      bodyFont: "Open Sans",
      titleWeight: "600",
      titleSpacing: "0",
    },
  },
  {
    match: (d) => /^10\.1109\//i.test(d.doi) || /ieee/i.test(d.container || d.publisher || ""),
    theme: {
      color: "#00629b",
      titleFont: "Roboto",
      bodyFont: "Roboto",
      titleWeight: "700",
      titleSpacing: "-0.01em",
      label: "IEEE",
    },
  },
  {
    match: (d) => d.source === "datacite",
    theme: {
      color: "#0f766e",
      titleFont: "Source Serif 4",
      bodyFont: "Source Sans 3",
      titleWeight: "700",
      titleSpacing: "0",
    },
  },
];

const loadedFontSets = new Set();

function themeFor(data) {
  const rule = JOURNAL_THEME_RULES.find((entry) => entry.match(data));
  const spec = rule
    ? typeof rule.theme === "function"
      ? rule.theme(data)
      : rule.theme
    : null;
  const base = spec ? { ...DEFAULT_THEME, ...spec } : { ...DEFAULT_THEME };
  const label =
    base.label ||
    (data.container || data.publisher || "Journal").slice(0, 32);
  return { ...base, label };
}

function cardStyle(theme) {
  const titleFallback =
    theme.titleFallback || "Georgia, Times New Roman, serif";
  const bodyFallback =
    theme.bodyFallback || "system-ui, -apple-system, sans-serif";
  const vars = [
    `--badge:${theme.color}`,
    `--accent:${theme.color}`,
    `--title-font:'${theme.titleFont}',${titleFallback}`,
    `--body-font:'${theme.bodyFont}',${bodyFallback}`,
    `--title-weight:${theme.titleWeight}`,
    `--title-spacing:${theme.titleSpacing}`,
    `--fs-scale:${custom.scale / 100}`,
    `--card-w:${custom.width}px`,
  ];
  if (theme.metaFont) vars.push(`--meta-font:'${theme.metaFont}',${bodyFallback}`);
  if (theme.titleColor) vars.push(`--title-color:${theme.titleColor}`);
  if (theme.textColor) vars.push(`--text-color:${theme.textColor}`);
  if (theme.metaColor) vars.push(`--meta-color:${theme.metaColor}`);
  if (theme.rule) vars.push(`--rule:${theme.rule}`);
  if (theme.ruleWidth) vars.push(`--rule-w:${theme.ruleWidth}`);
  if (theme.topbar) vars.push(`--topbar:${theme.topbar}`);
  if (theme.topbarHeight != null) vars.push(`--topbar-h:${theme.topbarHeight}`);
  if (theme.logoHeight) vars.push(`--logo-h:${theme.logoHeight}`);
  if (custom.ratio !== "auto") vars.push(`--ratio:${custom.ratio}`);
  return vars.join(";");
}

function fontCacheKey(theme) {
  if (theme.googleFonts != null) return theme.googleFonts || "system";
  return uniq([theme.titleFont, theme.bodyFont].filter(Boolean)).join("|");
}

function googleFontsQuery(theme) {
  if (theme.googleFonts != null) return theme.googleFonts;
  return uniq([theme.titleFont, theme.bodyFont].filter(Boolean))
    .map((family) => `family=${encodeURIComponent(family)}:wght@400;600;700;800`)
    .join("&");
}

// Self-hosted faces (declared in style.css via @font-face) just need
// FontFaceSet to pull them in; Google-hosted families get a stylesheet link.
function loadLocalFonts(theme) {
  if (!theme.localFonts || !document.fonts) return Promise.resolve();
  return Promise.all(
    theme.localFonts.flatMap((family) => [
      document.fonts.load(`400 1em '${family}'`),
      document.fonts.load(`700 1em '${family}'`),
    ])
  ).catch(() => undefined);
}

function ensureFonts(theme) {
  const local = loadLocalFonts(theme);
  const key = fontCacheKey(theme);
  const query = googleFontsQuery(theme);
  if (loadedFontSets.has(key) || !query) {
    loadedFontSets.add(key);
    const ready = document.fonts && document.fonts.ready
      ? document.fonts.ready.catch(() => undefined)
      : Promise.resolve();
    return Promise.all([local, ready]);
  }
  loadedFontSets.add(key);
  const linked = new Promise((resolve) => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    // crossorigin lets html-to-image read cssRules and embed the fonts at export
    link.crossOrigin = "anonymous";
    link.href = `https://fonts.googleapis.com/css2?${query}&display=swap`;
    const done = () => {
      const ready = document.fonts && document.fonts.ready
        ? document.fonts.ready.catch(() => undefined)
        : Promise.resolve();
      ready.then(resolve);
    };
    link.onload = done;
    link.onerror = () => resolve();
    document.head.appendChild(link);
    setTimeout(done, 500);
  });
  return Promise.all([local, linked]);
}

/* ---------- Render ---------- */
// Toggleable fields. `title` is mandatory (always in the shot).
const FIELD_DEFS = [
  { key: "authors", label: "Authors", has: (d) => (d.authors || []).length > 0 },
  { key: "affiliations", label: "Affiliations", has: (d) => (d.affiliations || []).length > 0 },
  { key: "meta", label: "Journal & date", has: (d) => !!(d.container || d.type || d.date || d.publisher) },
  { key: "abstract", label: "Abstract", has: (d) => !!d.abstract },
  { key: "doi", label: "DOI", has: (d) => !!d.doi },
];

let currentData = null;
const fieldOn = {}; // key -> boolean

// Appearance controls (font size %, card width px, aspect ratio, journal vs
// minimal styling, export pixel ratio).
const custom = {
  scale: 100,
  width: 760,
  ratio: "auto",
  style: "journal",
  pixelRatio: 2,
};

function activeTheme(data) {
  if (custom.style === "minimal") {
    const label = (data.container || data.publisher || "Journal").slice(0, 32);
    return { ...DEFAULT_THEME, label };
  }
  return themeFor(data);
}

function mastheadHtml(theme) {
  if (theme.kind !== "branded") {
    return `<span class="badge">${esc(theme.label)}</span>`;
  }
  const bits = [];
  if (theme.logo)
    bits.push(`<img src="${esc(theme.logo)}" alt="${esc(theme.label)}" crossorigin="anonymous">`);
  if (theme.wordmark)
    bits.push(`<span class="jname-word">${esc(theme.wordmark)}</span>`);
  if (theme.journalName)
    bits.push(`<span class="jname">${esc(theme.journalName)}</span>`);
  return `<div class="masthead-row">${bits.join("")}</div>`;
}

function buildCardHtml(data) {
  const theme = activeTheme(data);
  const parts = [mastheadHtml(theme)];
  parts.push(`<h2 class="title">${esc(data.title)}</h2>`);

  if (fieldOn.authors)
    parts.push(
      `<p class="authors">${formatAuthors(data.authors) || "<span class='more'>Authors unavailable</span>"}</p>`
    );

  if (fieldOn.affiliations && (data.affiliations || []).length) {
    const CAP = 6;
    const affs = data.affiliations.slice(0, CAP).map(esc).join(" · ");
    const more = data.affiliations.length > CAP ? ` <span class="more">+ ${data.affiliations.length - CAP} more</span>` : "";
    parts.push(`<p class="affils">${affs}${more}</p>`);
  }

  if (fieldOn.meta) {
    const metaBits = [];
    if (data.container && data.container !== theme.label) metaBits.push(`<span><b>${esc(data.container)}</b></span>`);
    if (data.type) metaBits.push(`<span>${esc(data.type)}</span>`);
    if (data.date) metaBits.push(`<span>${esc(data.date)}</span>`);
    if (data.publisher && data.publisher !== theme.label && !data.container) metaBits.push(`<span>${esc(data.publisher)}</span>`);
    if (metaBits.length) parts.push(`<div class="meta">${metaBits.join("")}</div>`);
  }

  if (fieldOn.abstract && data.abstract)
    parts.push(`<p class="abstract">${esc(data.abstract)}</p>`);

  if (fieldOn.doi)
    parts.push(
      `<div class="doi"><a href="${esc(data.url)}" target="_blank" rel="noopener">doi.org/${esc(data.doi)}</a><span class="mark">${DOISHOT_MARK}</span></div>`
    );
  else
    parts.push(`<div class="doi end"><span class="mark">${DOISHOT_MARK}</span></div>`);

  const ratioClass = custom.ratio !== "auto" ? " ratio-fixed" : "";
  return `<article class="card${ratioClass}" id="card" style="${cardStyle(theme)}">${parts.join("")}</article>`;
}

function rebuildCard() {
  const old = $("#card");
  if (!old) return;
  old.outerHTML = buildCardHtml(currentData);
}

function renderResult(data) {
  currentData = data;
  // Initialise toggles: on by default, but only for fields that have data.
  for (const f of FIELD_DEFS) fieldOn[f.key] = f.has(data);

  const toggles = FIELD_DEFS.map((f) => {
    const available = f.has(data);
    return `<label class="fld ${available ? "" : "off"}">
      <input type="checkbox" data-field="${f.key}" ${fieldOn[f.key] ? "checked" : ""} ${available ? "" : "disabled"}>
      <span>${f.label}</span>
    </label>`;
  }).join("");

  return ensureFonts(activeTheme(data)).then(() => {
    stage.innerHTML = `
    <div class="fields">
      <span class="fields-title">Include</span>
      <label class="fld locked"><input type="checkbox" checked disabled><span>Title</span></label>
      ${toggles}
    </div>
    <div class="appearance" id="appearance">
      <span class="ctl"><label for="ctl-style">Style</label>
        <select id="ctl-style">
          <option value="journal" ${custom.style === "journal" ? "selected" : ""}>Journal</option>
          <option value="minimal" ${custom.style === "minimal" ? "selected" : ""}>Minimal</option>
        </select></span>
      <span class="ctl"><label for="ctl-scale">Font size</label>
        <input type="range" id="ctl-scale" min="75" max="145" step="5" value="${custom.scale}">
        <output id="out-scale">${custom.scale}%</output></span>
      <span class="ctl"><label for="ctl-width">Width</label>
        <input type="range" id="ctl-width" min="560" max="1000" step="20" value="${custom.width}">
        <output id="out-width">${custom.width}px</output></span>
      <span class="ctl"><label for="ctl-ratio">Ratio</label>
        <select id="ctl-ratio">
          ${[["auto", "Auto"], ["16/9", "16:9"], ["4/3", "4:3"], ["1/1", "1:1"], ["4/5", "4:5"]]
            .map(([v, t]) => `<option value="${v}" ${custom.ratio === v ? "selected" : ""}>${t}</option>`).join("")}
        </select></span>
      <span class="ctl"><label for="ctl-px">Export</label>
        <select id="ctl-px">
          ${[1, 2, 3].map((n) => `<option value="${n}" ${custom.pixelRatio === n ? "selected" : ""}>${n}×</option>`).join("")}
        </select></span>
    </div>
    ${buildCardHtml(data)}
    <p class="copynote" id="copynote"></p>
    <div class="actions">
      <button class="primary" id="copyimg">⧉ Copy image</button>
      <button id="png">⬇ Download PNG</button>
      <button id="cite">Copy citation</button>
      <button id="bibtex">Copy BibTeX</button>
      <button id="link">Copy link</button>
    </div>
  `;

    stage.querySelectorAll('.fields input[data-field]').forEach((cb) =>
      cb.addEventListener("change", () => {
        fieldOn[cb.dataset.field] = cb.checked;
        rebuildCard();
      })
    );

    const onCtl = (id, fn) => {
      const el = $(id);
      el.addEventListener("input", () => { fn(el); rebuildCard(); });
    };
    onCtl("#ctl-scale", (el) => {
      custom.scale = Number(el.value);
      $("#out-scale").textContent = `${custom.scale}%`;
    });
    onCtl("#ctl-width", (el) => {
      custom.width = Number(el.value);
      $("#out-width").textContent = `${custom.width}px`;
    });
    onCtl("#ctl-ratio", (el) => { custom.ratio = el.value; });
    onCtl("#ctl-px", (el) => { custom.pixelRatio = Number(el.value); });
    $("#ctl-style").addEventListener("input", (e) => {
      custom.style = e.target.value;
      ensureFonts(activeTheme(currentData)).then(rebuildCard);
    });

    $("#copyimg").addEventListener("click", (e) => copyCardImage(e.target));
    $("#png").addEventListener("click", downloadPng);
    $("#cite").addEventListener("click", (e) => copyText(e.target, citation(data)));
    $("#bibtex").addEventListener("click", (e) => copyText(e.target, bibtex(data)));
    $("#link").addEventListener("click", (e) =>
      copyText(e.target, `${location.origin}${location.pathname}?doi=${encodeURIComponent(data.doi)}`)
    );
  });
}

/* ---------- Exports ---------- */
async function downloadPng() {
  const card = $("#card");
  const btn = $("#png");
  const prev = btn.textContent;
  btn.textContent = "Rendering…";
  btn.disabled = true;
  try {
    if (currentData) await ensureFonts(activeTheme(currentData));
    const dataUrl = await htmlToImage.toPng(card, {
      pixelRatio: custom.pixelRatio,
      backgroundColor: "#ffffff",
      style: { boxShadow: "none" },
    });
    const a = document.createElement("a");
    a.download = `doishot-${slug($("#card").querySelector(".title").textContent)}.png`;
    a.href = dataUrl;
    a.click();
    btn.textContent = "✓ Saved";
  } catch (e) {
    btn.textContent = "Export failed";
  }
  btn.disabled = false;
  setTimeout(() => (btn.textContent = prev), 1600);
}

function slug(s) {
  return (s || "paper").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 50);
}

// Copy the rendered card to the clipboard as a PNG image.
async function copyCardImage(btn) {
  const card = $("#card");
  if (!card) return false;
  const prev = btn ? btn.textContent : "";
  if (btn) { btn.textContent = "Rendering…"; btn.disabled = true; }
  let ok = false;
  try {
    if (currentData) await ensureFonts(activeTheme(currentData));
    if (!navigator.clipboard || !window.ClipboardItem) throw new Error("no-clipboard-api");
    const blob = await htmlToImage.toBlob(card, {
      pixelRatio: custom.pixelRatio,
      backgroundColor: "#ffffff",
      style: { boxShadow: "none" },
    });
    await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
    ok = true;
  } catch (_) {
    ok = false;
  }
  if (btn) {
    btn.textContent = ok ? "✓ Copied" : "Press ⌘V failed - use Download";
    btn.classList.toggle("ok", ok);
    btn.disabled = false;
    setTimeout(() => { btn.textContent = prev; btn.classList.remove("ok"); }, ok ? 1500 : 2400);
  }
  return ok;
}

function citation(d) {
  const names = (d.authors || []).map(authorName).filter(Boolean);
  let auth = names.slice(0, 3).join(", ");
  if (names.length > 3) auth += ", et al.";
  const where = d.container || d.publisher || "";
  return `${auth}${auth ? " " : ""}(${d.year || "n.d."}). ${d.title}.${where ? " " + where + "." : ""} https://doi.org/${d.doi}`;
}

function bibtex(d) {
  const first = (d.authors || []).map(authorName).filter(Boolean)[0] || "anon";
  const key = (first.split(/[\s,]+/).pop() || "anon").toLowerCase() + (d.year || "");
  const authors = (d.authors || [])
    .map((a) => {
      const fam = a.family || a.familyName || "";
      const giv = a.given || a.givenName || "";
      return fam && giv ? `${fam}, ${giv}` : a.name || authorName(a);
    })
    .filter(Boolean)
    .join(" and ");
  const isArxiv = /^10\.48550\/arxiv/i.test(d.doi);
  const entry = isArxiv ? "misc" : "article";
  const lines = [
    `@${entry}{${key.replace(/[^a-z0-9]/gi, "")},`,
    `  title   = {${d.title}},`,
    authors && `  author  = {${authors}},`,
    d.container && `  journal = {${d.container}},`,
    d.year && `  year    = {${d.year}},`,
    d.publisher && !d.container && `  publisher = {${d.publisher}},`,
    `  doi     = {${d.doi}},`,
    `  url     = {https://doi.org/${d.doi}}`,
    `}`,
  ].filter(Boolean);
  return lines.join("\n");
}

async function copyText(btn, text) {
  try {
    await navigator.clipboard.writeText(text);
    const prev = btn.textContent;
    btn.textContent = "✓ Copied";
    btn.classList.add("ok");
    setTimeout(() => {
      btn.textContent = prev;
      btn.classList.remove("ok");
    }, 1500);
  } catch (_) {
    window.prompt("Copy:", text);
  }
}

/* ---------- Usage tracking ---------- */
const trackedDois = new Set();

function trackingConfig() {
  const c = window.__DOISHOT_CONFIG || {};
  const url = (c.SUPABASE_URL || "").replace(/\/+$/, "");
  const key = c.SUPABASE_ANON_KEY || "";
  if (!url || !key) return null;
  return { url, key };
}

function clipTelemetryField(value, maxLen) {
  if (value == null || value === "") return null;
  const s = String(value);
  return s.length <= maxLen ? s : s.slice(0, maxLen);
}

function trackShot({ doi, source }) {
  if (!doi || trackedDois.has(doi)) return;
  const cfg = trackingConfig();
  if (!cfg) return;
  trackedDois.add(doi);

  fetch(`${cfg.url}/rest/v1/usage_events`, {
    method: "POST",
    keepalive: true,
    headers: {
      "Content-Type": "application/json",
      apikey: cfg.key,
      Authorization: `Bearer ${cfg.key}`,
      Prefer: "return=minimal",
    },
    body: JSON.stringify({
      doi: clipTelemetryField(doi, 200),
      source: clipTelemetryField(source, 50),
      surface: "web",
    }),
  }).catch(() => {});
}

/* ---------- States ---------- */
function showLoading(doi) {
  stage.innerHTML = `<div class="status"><span class="spinner"></span>Resolving <b>${esc(doi)}</b>…</div>`;
}
function showError(msg) {
  stage.innerHTML = `<div class="status error">${esc(msg)}</div>`;
}

/* ---------- Flow ---------- */
async function run(rawValue, { push = true } = {}) {
  const doi = normalizeDoi(rawValue);
  if (!doi) {
    showError("That doesn't look like a DOI. Try e.g. 10.1038/nature12373 or arXiv:2303.08774");
    return;
  }
  input.value = doi;
  goBtn.disabled = true;
  showLoading(doi);
  if (push) {
    const u = new URL(location.href);
    u.searchParams.set("doi", doi);
    history.replaceState(null, "", u);
  }
  try {
    const data = await resolve(doi);
    await renderResult(data);
    trackShot({ doi: data.doi, source: data.source });
    // The "shot" is taken: drop the image straight onto the clipboard.
    const note = $("#copynote");
    const copied = await copyCardImage(null);
    if (note)
      note.textContent = copied
        ? "✓ Snapshot copied to clipboard - paste it anywhere (⌘V)."
        : "Snapshot ready - use Copy image or Download PNG below.";
  } catch (e) {
    showError("Couldn't find that DOI. Check it's correct - it may be unregistered or temporarily unavailable.");
  }
  goBtn.disabled = false;
}

/* ---------- Wire up ---------- */
form.addEventListener("submit", (e) => {
  e.preventDefault();
  run(input.value);
});

document.querySelectorAll(".examples button").forEach((b) =>
  b.addEventListener("click", () => run(b.dataset.doi))
);

// Deep link: ?doi=… (works under any base path, proxy-friendly)
window.addEventListener("DOMContentLoaded", () => {
  const q = new URLSearchParams(location.search).get("doi");
  if (q) run(q, { push: false });
  else input.focus();
});
